### ISSUE TITLE
Does Herobrine generate structure this often?

### ISSUE THREAD

**Issue by jate-koh** [LunarEclipseStudios/From-The-Fog#31]
When venturing and exploring an ocean with a few of my friends into a sea.. 

We see sand **pyramids and mossy pyramids are generated almost everytime we got into new chunk.**

And at the end, this is how many pyramids it generated in the minimap's view. It seems to much to our liking and ruin much needed surprise for my friend.

![pyramid1](https://github.com/LunarEclipseStudios/From-The-Fog/assets/68505570/a107c692-bfd5-4b90-b449-eac715316d95)
![pyramid2](https://github.com/LunarEclipseStudios/From-The-Fog/assets/68505570/5ef2e500-55dd-4f53-bcb5-1ab754574ce9)

Plus, there are neither any (apparent) log in debug mode that going to tell me that structure is generated, nor there are any option to disable generation or reduce its chance. I would suggest adding all of that.

Thank you very much~!

**Comment by morceaudebois** [comment]
Having the same problem here :(

**Comment by Bret06** [comment]
Because this is a datapack we cannot allow for easy manipulation of how often structures generate. I didn't realize they spawn this often so I will be sure to have a look at it. If you have any other questions/suggestions please be sure to leave them on our [Discord](https://discord.lunareclipse.studio/).
