### ISSUE TITLE
Floating Herobrine

### ISSUE THREAD

**Issue by Whomandwhy** [LunarEclipseStudios/From-The-Fog#41]
![2](https://github.com/LunarEclipseStudios/From-The-Fog/assets/41106353/888d4482-c79e-4027-83d3-448b997cb6b3)
![image](https://github.com/LunarEclipseStudios/From-The-Fog/assets/41106353/dedda2ea-09ec-4022-8e15-ac4d1d008784)

Neat mod, but it seems to have some rancid incompatibilities (of which I am not certain of and admittedly going through the mod list to find my incompatible mod is not something im willing to do when the devs themselves dont seem interested in making an incompatibility list) I've seen several in the server, but I have none of the known ones, and thus am left with this buzzkill bug. Really kills the scares. Promising mod, hopefully in the future you'll add a list of incompatible mods from gathered knowledge via discord users bug reports.

**Comment by Bret06** [comment]
The reason we don't have an incompatible mod list is because the incompatibilities change per version. It all boils down to the way forge/fabric, and Minecraft updates. There is no possible way for us to keep an incompatible mod list maintained, thus is the reason we don't have one. If you're in the Discord server please leave things like this there as it has a higher chance of getting noticed.
